### ISSUE TITLE
Kill the "do you want to log in again" popup

### ISSUE THREAD

**Issue by philn** [Igalia/phpreport#308]
This popup is useless, please drop it and make the page refresh instead?

**Comment by aperezdc** [comment]
Or use a “ping-like” thing over `XmlHttpRequest` to keep the session alive.

**Comment by jaragunde** [comment]
I'd rather not kill the popup, most services show this kind of message when the session expires instead of redirecting you to the login page when you aren't looking.

Notice that a refresh only works in our deployment because it uses the http authentication headers, and the browser keeps them indefinitely. In a service using other login service, a refresh would take you to the login page and you would have to enter your credentials again.

**Comment by jaragunde** [comment]
> Or use a “ping-like” thing over XmlHttpRequest to keep the session alive.

Funnily enough, the ping sent to the server to check if the session is active also has this side effect. Anyways, the session could be closed by the server in the time between two pings so this mechanism still needs to be in place.

**Comment by jaragunde** [comment]
The impact/frequency of these popups has been mitigated by #382. I still think the popup is necessary so I'm closing the bug.
