### ISSUE TITLE
Preselect the current time when adding a new task

### ISSUE THREAD

**Issue by xtuc** [Igalia/phpreport#442]
Each time i'm creating a new task I need to check the current time on my desktop. I think that this could be automatically selected for me.

Alternatively It could be displayed on the page so that I can just copy/past it.

The annoying part is about the handling of timezones.

**Comment by jaragunde** [comment]
> Each time i'm creating a new task I need to check the current time on my desktop. I think that this could be automatically selected for me.
> 

The application used to set the current time as "end time" of the task, because we were supposing that users would fill a task as soon as they ended working on that, but we stopped doing that so we could fit different use cases:
* where people fill their journey for all day in advance.
* where people fill their tasks in retrospect, at the end of the day or the week.

Maybe we could re-enable auto-fill of the time fields, under a user-selected choice, like: "never", "init time is NOW", "end time is NOW".

> Alternatively It could be displayed on the page so that I can just copy/past it.
> 

Typing times shouldn't be hard, there are several shortcuts you can take, like not typing the colon or typing incomplete times, e.g. if you type "9" it becomes "09:00", if you type "1015" it becomes "10:15". 

> The annoying part is about the handling of timezones.

You shouldn't have to handle timezones, just fill your tasks in your current timezone. Am I understanding correctly?

**Comment by xtuc** [comment]
> Maybe we could re-enable auto-fill of the time fields, under a user-selected choice, like: "never", "init time is NOW", "end time is NOW".

That would be great! My use case is: adding a new task whenever I start working (I'm in the Coding Experience program so it might be a bit different).

> Typing times shouldn't be hard, there are several shortcuts you can take, like not typing the colon or typing incomplete times, e.g. if you type "9" it becomes "09:00", if you type "1015" it becomes "10:15".

Yes, I have noticed that. My point is more about having to lookup the current time.

> The annoying part is about the handling of timezones.

Sorry I meant of your (phpreport) side, I'm frequently chaning timezone (and I guess Igalia folks are too). It depends if the exact times matter or just the amount of hours.

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.

The new timer feature will solve this.
